### ISSUE TITLE
Derive PartialOrd and Ord for CanonicalCombiningClass?

### ISSUE THREAD

**Issue by theodore-s-beers** [yeslogic/unicode-canonical-combining-class#3]
This crate became useful to me for implementing the Unicode Collation Algorithm. There's a [point](https://unicode.org/reports/tr10/#UTS10-D34) in the algorithm at which it is necessary to check that the combining class of a character is less than that of one or more preceding characters. I was able to fork the repo, add `PartialOrd` and `Ord` to the `derive` list in `tables.rs`—though I know the file isn't meant to be edited manually—and everything worked fine.

Do you think it would make sense to derive those traits by default? I assume this would involve some modification to your fork of `ucd-generate`. Perhaps at [this line](https://github.com/yeslogic/ucd-generate/blob/3b21e76e6bb551054dc9a574ecc596fdc0d20a23/src/writer.rs#L370)? Anyway, it's up to you. I was glad to find this library.

**Comment by theodore-s-beers** [comment]
I later realized that I can cast to the discriminant value, i.e. `CanonicalCombiningClass::Foo as u8`. Maybe that's good enough. It allows me to use the crate as-is. Sorry if this is a bother.

**Comment by adrianwong** [comment]
Hi @theodore-s-beers, not a bother at all. I don't see why not, given that enums generated by the `ranges_to_rust_enum_with_custom_discriminants` function have custom discriminant values that you can cast to anyway (as you've already figured out).

Having said that, I've been away from this space for a while, so I'll check in with @wezm before making this change.

**Comment by adrianwong** [comment]
This has been resolved in v0.3.0.
