### ISSUE TITLE
Update to Unicode 15?

### ISSUE THREAD

**Issue by theodore-s-beers** [yeslogic/unicode-canonical-combining-class#5]
I was wondering when you think it would make sense to update this library to Unicode 15 (which came out earlier this week). I already got it working in [my fork](https://github.com/theodore-s-beers/unicode-canonical-combining-class/commit/5f4db62509559469672f02e3949a6b9c15733a4f), but it occurred to me that you might not want to update immediately. I was also hesitant to open a PR because the generated file `tables.rs` includes a reference to the directory against which `ucd-generate` was run (currently `/home/wmoore/Downloads/ucd-14.0`). So when I ran it, that became `/Users/theo/Desktop/ucd-15.0`, which probably doesn't belong in your library.

Thanks as always!

**Comment by wezm** [comment]
Hi Theo, I don't think there's any issue with updating to Unicode 15 now. Cargo's versioning will allow us to stay on the previous version until we're ready to upgrade. The path in `tables.rs` is fine too. It mainly serves to document how `ucd-generate` was invoked and a rudimentary reminder of the UCD version used.

So, if you wanted to open a PR to do the Unicode 15 upgrade that would be fine.

**Comment by wezm** [comment]
Actually I'm working on updating all our unicode crates to 15 now, so if you hold off I'll do the update for this one too.

**Comment by theodore-s-beers** [comment]
Yeah, I was thinking the work for `ucd-generate` looked a bit more extensive, anyway. This crate is the least of it. I'm still happy to open a PR if you change your mind. Thanks!

**Comment by theodore-s-beers** [comment]
Thanks again for this. Do you think that the new version should be published to crates.io?

**Comment by wezm** [comment]
Ahh yeah I'm working my way through them all but got sidetracked with another crate the other day. I'll get this one out when I'm back at work tomorrow.

**Comment by wezm** [comment]
New version has been published
